### ISSUE TITLE
Final report delegation

### ISSUE THREAD

**Issue by maddijd03** [Ellen123R/ESus-Project#51]

**Comment by Ellen123R** [comment]
I've highlighted some parts I've grouped together, but we can discuss actual delegation tomorrow

**Comment by Ellen123R** [comment]
Might also be worth asking Ravi whether we need to create and submit an improved Work Breakdown Structure as part of the requirements (it's not in the criteria on Canvas)

**Comment by Ellen123R** [comment]
Also will be worth asking Ravi how many pages will be expected
